docker:
  compose: docker-compose.yml

fabric:
  keystore_path: ./hfc-key-store
  channel: mychannel
  orderer:
    host: orderer.example.com
    port: 7050
  peers:
    peer0.org1.example.com:
      environment:
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp
      configtx_file: /etc/hyperledger/configtx/channel.tx
  clients:
    cli:
      environment:
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
